content:
  - name: post
    label: Posts
    path: src/content/posts
    filename: "{fields.name}.md"
    type: collection
    view:
      fields: [name, dateCreated]
      primary: name
      sort: [dateCreated, name]
    fields:
      - name: name
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: dateCreated
        label: Created
        type: date
        required: true
      - name: body
        label: Body
        type: rich-text
